name: Bug Report
description: Report a problem or unexpected behavior in XFast Manager
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve XFast Manager! Please fill out the form below.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short, clear description of the bug.
      placeholder: "Installation fails when dragging a ZIP file"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions so we can reproduce the issue.
      placeholder: |
        1. Open XFast Manager
        2. Drag a ZIP addon into the window
        3. Click Install
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: XFast Manager Version
      description: You can find this in Settings.
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: OS name and version.
      placeholder: "Windows 11 25H2 / macOS 14.3 / Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: arch
    attributes:
      label: CPU Architecture
      description: e.g., x64, arm64 (Apple Silicon).
      placeholder: "x64"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please paste relevant logs or attach the log file.
        Log locations:
        - Windows: %LOCALAPPDATA%\com.xfastmanager.tool\logs
        - macOS: ~/Library/Application Support/com.xfastmanager.tool/logs
        - Linux: ~/.local/share/com.xfastmanager.tool/logs
      render: text
    validations:
      required: true

  - type: input
    id: xplane_version
    attributes:
      label: X-Plane Version (optional)
      placeholder: "12.4.0"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Recordings (optional)
      description: Drag and drop images or video files here.
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional Context (optional)
      description: Anything else that might help.
    validations:
      required: false
